# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hipchat-api}
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{David Czarnecki}]
  s.date = %q{2011-09-09}
  s.description = %q{Ruby gem for interacting with HipChat}
  s.email = %q{czarneckid@acm.org}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    ".travis.yml",
    "CHANGLOG.markdown",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "hipchat-api.gemspec",
    "lib/hipchat-api.rb",
    "spec/fakeweb/rooms_create_response.json",
    "spec/fakeweb/rooms_delete_response.json",
    "spec/fakeweb/rooms_history_response.json",
    "spec/fakeweb/rooms_list_response.json",
    "spec/fakeweb/rooms_message_response.json",
    "spec/fakeweb/rooms_show_response.json",
    "spec/fakeweb/users_create_response.json",
    "spec/fakeweb/users_delete_response.json",
    "spec/fakeweb/users_list_response.json",
    "spec/fakeweb/users_show_response.json",
    "spec/fakeweb/users_update_response.json",
    "spec/hipchat-api_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/czarneckid/hipchat-api}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.8}
  s.summary = %q{Ruby gem for interacting with HipChat}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

